### ISSUE TITLE
Installer changes "Plugin Name:" key in plugin file as well as value

### ISSUE THREAD

**Issue by AndrewFeeney** [ArcFramework/installer#2]

**Comment by pxslip** [comment]
Looking at this and am wondering how you want to approach it. My first thought is to go through the [plugin](https://github.com/ArcFramework/plugin) and replace `Plugin Name` with a unique search syntax - something like `<<Plugin Name>>`. Should this be expanded to include all of the replacement strings?

**Comment by AndrewFeeney** [comment]
I did think of that. My only hesitation was that a unique search string like that would render the plugin unworkable if someone cloned the repository until they'd manually been through the files and changed the text. Obviously we want people to use the installer instead of manually cloning, but whichever way people go about it I want it to be as easy as possible to get to coding right away. In this case I think we should be safe to change `Plugin Name: Plugin Name` to `Plugin Name: PluginName` and update the installer code to search for `PluginName` instead of `Plugin Name`. What do you think about that?

**Comment by AndrewFeeney** [comment]
Fixed in #3

**Comment by AndrewFeeney** [comment]
In the end I remembered why I didn't use `MyPlugin` in the first place, which was to avoid confusion with the namespace. I've changed it to `My Plugin Name` for now.
